In [3]:
import numpy as np

x = np.arange(1, 10).reshape((3,3))

x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
y = np.transpose(x)
y

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [10]:
z = np.arange(1,26).reshape((5,5))
z

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [12]:
np.transpose(z)

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

## Tema

Functia `transpose` pentru orice matrice patratica de dimensiune `n`.

Varianta folosind functia `zip`